server:
  port: 8762

spring:
  application:
    name: zuul-server
  profiles:
    active: dev
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
security:
  basic:
    enabled: false
management:
  security:
    enabled: false