server:
  port: 8081
spring:
  application:
    name: user-service
  profiles:
    active: dev
eureka:
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://192.168.0.5:8761/eureka/
    register-with-eureka: false
    fetch-registry: false