server:
  port: 8082

spring:
  application:
    name: order-service
  profiles:
    active: dev
eureka:
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false